package com.ego.pojo;

import java.io.Serializable;

public class AdminWithBLOBs extends Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.nav_list
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    private String navList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.todolist
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    private String todolist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.nav_list
     *
     * @return the value of t_admin.nav_list
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    public String getNavList() {
        return navList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.nav_list
     *
     * @param navList the value for t_admin.nav_list
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    public void setNavList(String navList) {
        this.navList = navList == null ? null : navList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.todolist
     *
     * @return the value of t_admin.todolist
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    public String getTodolist() {
        return todolist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.todolist
     *
     * @param todolist the value for t_admin.todolist
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    public void setTodolist(String todolist) {
        this.todolist = todolist == null ? null : todolist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Apr 08 09:20:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", navList=").append(navList);
        sb.append(", todolist=").append(todolist);
        sb.append("]");
        return sb.toString();
    }
}