package com.ego.mapper;

import com.ego.pojo.Brand;
import com.ego.pojo.BrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    long countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    List<Brand> selectByExampleWithBLOBs(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    Brand selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    int updateByPrimaryKey(Brand record);
}