package com.ego.mapper;

import com.ego.pojo.GoodsImages;
import com.ego.pojo.GoodsImagesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    long countByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int deleteByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int insert(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int insertSelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    List<GoodsImages> selectByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    GoodsImages selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int updateByExample(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    int updateByPrimaryKey(GoodsImages record);
}