package com.ego.mapper;

import com.ego.pojo.GoodsAttribute;
import com.ego.pojo.GoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    long countByExample(GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int deleteByExample(GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int insert(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int insertSelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    List<GoodsAttribute> selectByExampleWithBLOBs(GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    List<GoodsAttribute> selectByExample(GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    GoodsAttribute selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsAttribute record, @Param("example") GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsAttribute record, @Param("example") GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByExample(@Param("record") GoodsAttribute record, @Param("example") GoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    int updateByPrimaryKey(GoodsAttribute record);
}