package com.ego.pojo;

import java.io.Serializable;

public class Brand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.logo
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.url
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.sort
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private Byte sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.cat_name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private String catName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.parent_cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private Integer parentCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private Integer catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.is_hot
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private Byte isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.desc
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.id
     *
     * @return the value of t_brand.id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.id
     *
     * @param id the value for t_brand.id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.name
     *
     * @return the value of t_brand.name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.name
     *
     * @param name the value for t_brand.name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.logo
     *
     * @return the value of t_brand.logo
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.logo
     *
     * @param logo the value for t_brand.logo
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.url
     *
     * @return the value of t_brand.url
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.url
     *
     * @param url the value for t_brand.url
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.sort
     *
     * @return the value of t_brand.sort
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.sort
     *
     * @param sort the value for t_brand.sort
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.cat_name
     *
     * @return the value of t_brand.cat_name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.cat_name
     *
     * @param catName the value for t_brand.cat_name
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.parent_cat_id
     *
     * @return the value of t_brand.parent_cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public Integer getParentCatId() {
        return parentCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.parent_cat_id
     *
     * @param parentCatId the value for t_brand.parent_cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setParentCatId(Integer parentCatId) {
        this.parentCatId = parentCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.cat_id
     *
     * @return the value of t_brand.cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.cat_id
     *
     * @param catId the value for t_brand.cat_id
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.is_hot
     *
     * @return the value of t_brand.is_hot
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.is_hot
     *
     * @param isHot the value for t_brand.is_hot
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.desc
     *
     * @return the value of t_brand.desc
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.desc
     *
     * @param desc the value for t_brand.desc
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand
     *
     * @mbg.generated Fri Mar 29 10:59:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", logo=").append(logo);
        sb.append(", url=").append(url);
        sb.append(", sort=").append(sort);
        sb.append(", catName=").append(catName);
        sb.append(", parentCatId=").append(parentCatId);
        sb.append(", catId=").append(catId);
        sb.append(", isHot=").append(isHot);
        sb.append(", desc=").append(desc);
        sb.append("]");
        return sb.toString();
    }
}