package com.ego.pojo;

import java.io.Serializable;

public class GoodsAttribute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Short typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_index
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Byte attrIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Byte attrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_input_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Byte attrInputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Byte attrOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attribute.attr_values
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String attrValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_id
     *
     * @return the value of t_goods_attribute.attr_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_id
     *
     * @param attrId the value for t_goods_attribute.attr_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_name
     *
     * @return the value of t_goods_attribute.attr_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_name
     *
     * @param attrName the value for t_goods_attribute.attr_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.type_id
     *
     * @return the value of t_goods_attribute.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.type_id
     *
     * @param typeId the value for t_goods_attribute.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.type_name
     *
     * @return the value of t_goods_attribute.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.type_name
     *
     * @param typeName the value for t_goods_attribute.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_index
     *
     * @return the value of t_goods_attribute.attr_index
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Byte getAttrIndex() {
        return attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_index
     *
     * @param attrIndex the value for t_goods_attribute.attr_index
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrIndex(Byte attrIndex) {
        this.attrIndex = attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_type
     *
     * @return the value of t_goods_attribute.attr_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Byte getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_type
     *
     * @param attrType the value for t_goods_attribute.attr_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrType(Byte attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_input_type
     *
     * @return the value of t_goods_attribute.attr_input_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Byte getAttrInputType() {
        return attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_input_type
     *
     * @param attrInputType the value for t_goods_attribute.attr_input_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrInputType(Byte attrInputType) {
        this.attrInputType = attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_order
     *
     * @return the value of t_goods_attribute.attr_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Byte getAttrOrder() {
        return attrOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_order
     *
     * @param attrOrder the value for t_goods_attribute.attr_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrOrder(Byte attrOrder) {
        this.attrOrder = attrOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attribute.attr_values
     *
     * @return the value of t_goods_attribute.attr_values
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getAttrValues() {
        return attrValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attribute.attr_values
     *
     * @param attrValues the value for t_goods_attribute.attr_values
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setAttrValues(String attrValues) {
        this.attrValues = attrValues == null ? null : attrValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attribute
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attrId=").append(attrId);
        sb.append(", attrName=").append(attrName);
        sb.append(", typeId=").append(typeId);
        sb.append(", typeName=").append(typeName);
        sb.append(", attrIndex=").append(attrIndex);
        sb.append(", attrType=").append(attrType);
        sb.append(", attrInputType=").append(attrInputType);
        sb.append(", attrOrder=").append(attrOrder);
        sb.append(", attrValues=").append(attrValues);
        sb.append("]");
        return sb.toString();
    }
}