package com.ego.pojo;

import java.io.Serializable;

public class GoodsImages implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_images.img_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_images.goods_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_images.image_url
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_images.img_id
     *
     * @return the value of t_goods_images.img_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_images.img_id
     *
     * @param imgId the value for t_goods_images.img_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_images.goods_id
     *
     * @return the value of t_goods_images.goods_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_images.goods_id
     *
     * @param goodsId the value for t_goods_images.goods_id
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_images.image_url
     *
     * @return the value of t_goods_images.image_url
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_images.image_url
     *
     * @param imageUrl the value for t_goods_images.image_url
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_images
     *
     * @mbg.generated Fri Mar 29 16:03:23 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", imgId=").append(imgId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append("]");
        return sb.toString();
    }
}