package com.ego.pojo;

import java.io.Serializable;

public class GoodsSpec implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.spec_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Integer specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.spec_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String specName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Short typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.spec_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Byte specOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_spec.spec_value
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String specValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_spec
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.spec_id
     *
     * @return the value of t_goods_spec.spec_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Integer getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.spec_id
     *
     * @param specId the value for t_goods_spec.spec_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setSpecId(Integer specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.spec_name
     *
     * @return the value of t_goods_spec.spec_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.spec_name
     *
     * @param specName the value for t_goods_spec.spec_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.type_id
     *
     * @return the value of t_goods_spec.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.type_id
     *
     * @param typeId the value for t_goods_spec.type_id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.type_name
     *
     * @return the value of t_goods_spec.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.type_name
     *
     * @param typeName the value for t_goods_spec.type_name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.spec_order
     *
     * @return the value of t_goods_spec.spec_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Byte getSpecOrder() {
        return specOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.spec_order
     *
     * @param specOrder the value for t_goods_spec.spec_order
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setSpecOrder(Byte specOrder) {
        this.specOrder = specOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_spec.spec_value
     *
     * @return the value of t_goods_spec.spec_value
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getSpecValue() {
        return specValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_spec.spec_value
     *
     * @param specValue the value for t_goods_spec.spec_value
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setSpecValue(String specValue) {
        this.specValue = specValue == null ? null : specValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_spec
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", specId=").append(specId);
        sb.append(", specName=").append(specName);
        sb.append(", typeId=").append(typeId);
        sb.append(", typeName=").append(typeName);
        sb.append(", specOrder=").append(specOrder);
        sb.append(", specValue=").append(specValue);
        sb.append("]");
        return sb.toString();
    }
}