package com.ego.pojo;

import java.io.Serializable;

public class GoodsType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.id
     *
     * @return the value of t_goods_type.id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.id
     *
     * @param id the value for t_goods_type.id
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.name
     *
     * @return the value of t_goods_type.name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.name
     *
     * @param name the value for t_goods_type.name
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbg.generated Fri Mar 29 16:47:00 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}