package com.ego.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Byte shippingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.consignee
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.country
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.province
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.city
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.district
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.twon
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer twon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.address
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.zipcode
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.mobile
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.email
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String shippingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String shippingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String payCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String payName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.invoice_title
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal shippingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal userMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.coupon_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.integral
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.integral_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal integralMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.add_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer shippingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.confirm_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Integer payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_prom_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Short orderPromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_prom_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal orderPromAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.discount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String userNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.admin_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String adminNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.parent_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private String parentSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_distribut
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private Byte isDistribut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_sn
     *
     * @return the value of t_order.order_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_sn
     *
     * @param orderSn the value for t_order.order_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_status
     *
     * @return the value of t_order.shipping_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Byte getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_status
     *
     * @param shippingStatus the value for t_order.shipping_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setShippingStatus(Byte shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_status
     *
     * @return the value of t_order.pay_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_status
     *
     * @param payStatus the value for t_order.pay_status
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.consignee
     *
     * @return the value of t_order.consignee
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.consignee
     *
     * @param consignee the value for t_order.consignee
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.country
     *
     * @return the value of t_order.country
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.country
     *
     * @param country the value for t_order.country
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.province
     *
     * @return the value of t_order.province
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.province
     *
     * @param province the value for t_order.province
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.city
     *
     * @return the value of t_order.city
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.city
     *
     * @param city the value for t_order.city
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.district
     *
     * @return the value of t_order.district
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.district
     *
     * @param district the value for t_order.district
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.twon
     *
     * @return the value of t_order.twon
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getTwon() {
        return twon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.twon
     *
     * @param twon the value for t_order.twon
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setTwon(Integer twon) {
        this.twon = twon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.address
     *
     * @return the value of t_order.address
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.address
     *
     * @param address the value for t_order.address
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.zipcode
     *
     * @return the value of t_order.zipcode
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.zipcode
     *
     * @param zipcode the value for t_order.zipcode
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.mobile
     *
     * @return the value of t_order.mobile
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.mobile
     *
     * @param mobile the value for t_order.mobile
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.email
     *
     * @return the value of t_order.email
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.email
     *
     * @param email the value for t_order.email
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_code
     *
     * @return the value of t_order.shipping_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_code
     *
     * @param shippingCode the value for t_order.shipping_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_name
     *
     * @return the value of t_order.shipping_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_name
     *
     * @param shippingName the value for t_order.shipping_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_code
     *
     * @return the value of t_order.pay_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_code
     *
     * @param payCode the value for t_order.pay_code
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_name
     *
     * @return the value of t_order.pay_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_name
     *
     * @param payName the value for t_order.pay_name
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice_title
     *
     * @return the value of t_order.invoice_title
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice_title
     *
     * @param invoiceTitle the value for t_order.invoice_title
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_price
     *
     * @return the value of t_order.goods_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_price
     *
     * @param goodsPrice the value for t_order.goods_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_price
     *
     * @return the value of t_order.shipping_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getShippingPrice() {
        return shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_price
     *
     * @param shippingPrice the value for t_order.shipping_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setShippingPrice(BigDecimal shippingPrice) {
        this.shippingPrice = shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_money
     *
     * @return the value of t_order.user_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_money
     *
     * @param userMoney the value for t_order.user_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.coupon_price
     *
     * @return the value of t_order.coupon_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.coupon_price
     *
     * @param couponPrice the value for t_order.coupon_price
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.integral
     *
     * @return the value of t_order.integral
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.integral
     *
     * @param integral the value for t_order.integral
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.integral_money
     *
     * @return the value of t_order.integral_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getIntegralMoney() {
        return integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.integral_money
     *
     * @param integralMoney the value for t_order.integral_money
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setIntegralMoney(BigDecimal integralMoney) {
        this.integralMoney = integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_amount
     *
     * @return the value of t_order.order_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_amount
     *
     * @param orderAmount the value for t_order.order_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.add_time
     *
     * @return the value of t_order.add_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.add_time
     *
     * @param addTime the value for t_order.add_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_time
     *
     * @return the value of t_order.shipping_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_time
     *
     * @param shippingTime the value for t_order.shipping_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setShippingTime(Integer shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.confirm_time
     *
     * @return the value of t_order.confirm_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.confirm_time
     *
     * @param confirmTime the value for t_order.confirm_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setConfirmTime(Integer confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_prom_id
     *
     * @return the value of t_order.order_prom_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Short getOrderPromId() {
        return orderPromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_prom_id
     *
     * @param orderPromId the value for t_order.order_prom_id
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderPromId(Short orderPromId) {
        this.orderPromId = orderPromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_prom_amount
     *
     * @return the value of t_order.order_prom_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getOrderPromAmount() {
        return orderPromAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_prom_amount
     *
     * @param orderPromAmount the value for t_order.order_prom_amount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setOrderPromAmount(BigDecimal orderPromAmount) {
        this.orderPromAmount = orderPromAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount
     *
     * @return the value of t_order.discount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount
     *
     * @param discount the value for t_order.discount
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_note
     *
     * @return the value of t_order.user_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getUserNote() {
        return userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_note
     *
     * @param userNote the value for t_order.user_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setUserNote(String userNote) {
        this.userNote = userNote == null ? null : userNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.admin_note
     *
     * @return the value of t_order.admin_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getAdminNote() {
        return adminNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.admin_note
     *
     * @param adminNote the value for t_order.admin_note
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setAdminNote(String adminNote) {
        this.adminNote = adminNote == null ? null : adminNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.parent_sn
     *
     * @return the value of t_order.parent_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public String getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.parent_sn
     *
     * @param parentSn the value for t_order.parent_sn
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setParentSn(String parentSn) {
        this.parentSn = parentSn == null ? null : parentSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_distribut
     *
     * @return the value of t_order.is_distribut
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public Byte getIsDistribut() {
        return isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_distribut
     *
     * @param isDistribut the value for t_order.is_distribut
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    public void setIsDistribut(Byte isDistribut) {
        this.isDistribut = isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Apr 11 14:20:20 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", userId=").append(userId);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", shippingStatus=").append(shippingStatus);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", consignee=").append(consignee);
        sb.append(", country=").append(country);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", twon=").append(twon);
        sb.append(", address=").append(address);
        sb.append(", zipcode=").append(zipcode);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", shippingCode=").append(shippingCode);
        sb.append(", shippingName=").append(shippingName);
        sb.append(", payCode=").append(payCode);
        sb.append(", payName=").append(payName);
        sb.append(", invoiceTitle=").append(invoiceTitle);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", shippingPrice=").append(shippingPrice);
        sb.append(", userMoney=").append(userMoney);
        sb.append(", couponPrice=").append(couponPrice);
        sb.append(", integral=").append(integral);
        sb.append(", integralMoney=").append(integralMoney);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", addTime=").append(addTime);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", confirmTime=").append(confirmTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", orderPromId=").append(orderPromId);
        sb.append(", orderPromAmount=").append(orderPromAmount);
        sb.append(", discount=").append(discount);
        sb.append(", userNote=").append(userNote);
        sb.append(", adminNote=").append(adminNote);
        sb.append(", parentSn=").append(parentSn);
        sb.append(", isDistribut=").append(isDistribut);
        sb.append("]");
        return sb.toString();
    }
}